# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileXTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file_course_location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filextag',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager_v1.File'),
        ),
        migrations.AddField(
            model_name='filextag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager_v1.Tag'),
        ),
    ]
