# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0004_auto_20180814_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_importance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
