# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0006_auto_20180904_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_id',
            new_name='file_unique_id',
        ),
    ]
