# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0007_auto_20180904_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursextag',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursextag',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseXTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
