# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0003_auto_20180814_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=1000, unique=True)),
                ('course_download_date', models.CharField(max_length=1000, unique=True)),
                ('course_revised', models.BooleanField(default=False, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FileXTag',
            new_name='CourseXTag',
        ),
        migrations.RemoveField(
            model_name='coursextag',
            name='file_id',
        ),
        migrations.AddField(
            model_name='coursextag',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_manager_v1.Course'),
            preserve_default=False,
        ),
    ]
