# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=1000, unique=True)),
                ('course_download_date', models.CharField(max_length=1000, unique=True)),
                ('course_revised', models.BooleanField(default=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseXTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager_v1.Course')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000, unique=True)),
                ('file_course_location', models.CharField(default='', max_length=1000, unique=True)),
                ('file_directory', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('tag_importance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='coursextag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager_v1.Tag'),
        ),
    ]
