# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=1000, unique=True)),
                ('course_download_date', models.CharField(max_length=1000)),
                ('course_revised', models.BooleanField(default=False)),
                ('course_download_available', models.BooleanField(default=False)),
                ('course_error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id_number', models.IntegerField()),
                ('tag_id_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000)),
                ('file_course_location', models.CharField(default='', max_length=1000, unique=True)),
                ('file_directory', models.CharField(max_length=1000, unique=True)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('tag_importance', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='courselanguage',
            unique_together=set([('course_id', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='course_tag',
            unique_together=set([('course_id_number', 'tag_id_number')]),
        ),
    ]
