# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=500)),
                ('next_lesson_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='lesson_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
