# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0002_auto_20180814_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_course_location',
            field=models.CharField(default='', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_directory',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
