# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0002_auto_20181003_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_identifier',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
