# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0003_lesson_lesson_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id_number', models.IntegerField()),
                ('tag_id_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Tag',
        ),
        migrations.AlterUniqueTogether(
            name='lesson_tag',
            unique_together=set([('lesson_id_number', 'tag_id_number')]),
        ),
    ]
