# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0005_lesson_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_uri', models.CharField(max_length=500)),
                ('concept_uri_alternate', models.CharField(max_length=500)),
                ('concept_label', models.CharField(max_length=100)),
                ('concept_language', models.CharField(max_length=10)),
            ],
        ),
    ]
