# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_v1', '0006_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_uri',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
